---
- name: "Setting DHCP"
  when: vm_id is defined
  ansible.builtin.command: "qm set {{ vm_id }} --ipconfig0 ip=dhcp"
  register: "output_cloud_init"
  changed_when: output_cloud_init.rc == 0 and output_cloud_init.stderr == ""
